version: "3.8"

volumes:
    db:

services:
    db:
        image: "postgres"
        restart: always
        environment:
            POSTGRES_USER: "anarchist"
            POSTGRES_PASSWORD: ${DBPASS}
            POSTGRES_DB: "db"
        volumes:
            - db:/var/lib/postgresql/data

    anarchy:
        image: "anarchy"
        build: ./anarchonet
        environment:
            SECRET: ${SECRET}
            dbname: "db"
            dbuser: "anarchist"
            dbpass: ${DBPASS}
            USESSL: "false"
        depends_on:
            - db

    productionproxy:
        image: "productionproxy"
        build: .
        ports:
            - 8000:80
            - 8443:443
        depends_on:
            - anarchy
        volumes:
            - ./certs:/etc/certs
