version: "3.8"

volumes:
    db:

services:
    db:
        image: "postgres"
        restart: always
        environment:
            POSTGRES_USER: "anarchist"
            POSTGRES_PASSWORD: ${DBPASS}
            POSTGRES_DB: "db"
        volumes:
            - db:/var/lib/postgresql/data

    anarchy:
        image: "anarchy"
        build: .
        environment:
            SECRET: ${SECRET}
            dbname: "db"
            dbuser: "anarchist"
            dbpass: ${DBPASS}
            USESSL: "false"
        depends_on:
            - db
        ports:
            - 8000:8000
